name: Streamprocessor integration PR tests
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

# This will cancel running workflows of the latest commit prior to closing PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  compile-application:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Maven compile
        shell: bash
        run: |
          mvn clean compile

      - name: Maven test
        shell: bash
        run: |
          mvn test
